"""
Django settings for JobPilot project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY manquante. "
        "Définissez la variable d’environnement SECRET_KEY (ou DJANGO_SECRET_KEY)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG").lower() in ("true", "1", "yes")
ENVIRONMENT = os.getenv("ENVIRONMENT").lower()
# Sécurité HTTPS uniquement en production (évite la redirection HTTPS avec runserver en local)
_PROD_SECURITY = (not DEBUG) and (ENVIRONMENT == "production")

# Paramètres de sécurité (toujours définis pour satisfaire check —deploy)
SECURE_SSL_REDIRECT = _PROD_SECURITY
SESSION_COOKIE_SECURE = _PROD_SECURITY
CSRF_COOKIE_SECURE = _PROD_SECURITY
SECURE_HSTS_SECONDS = 31536000 if _PROD_SECURITY else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = _PROD_SECURITY
SECURE_HSTS_PRELOAD = _PROD_SECURITY
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if _PROD_SECURITY else None

# Configuration du domaine du site
SITE_URL = os.getenv('SITE_URL', 'https://jobpilot-ai.fr')
# Extraire le nom de domaine pour ALLOWED_HOSTS (sans https://)
_site_domain = SITE_URL.replace('https://', '').replace('http://', '').rstrip('/')

ALLOWED_HOSTS = [
    '10.192.66.109', 
    'localhost', 
    '127.0.0.1', 
    'autohypnotic-lashay-undecretory.ngrok-free.dev',
    _site_domain,
    'jobpilot-ai.fr',
    'www.jobpilot-ai.fr',
    'jobpilot-ai-dpdcabeafpdxc0gc.francecentral-01.azurewebsites.net',
    # --- Les IPs internes d'Azure pour les Health Checks ---
    '169.254.129.4',
    '169.254.130.1',
    '169.254.130.3',
    '169.254.130.4',
    '169.254.129.2',
]
CSRF_TRUSTED_ORIGINS = [
    'https://autohypnotic-lashay-undecretory.ngrok-free.dev',
    SITE_URL,
    'https://jobpilot-ai.fr',
    'https://www.jobpilot-ai.fr'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'users.apps.UsersConfig',
    'resumes',
    'matching',
    'dashboard',
    'subscriptions',

# --- Allauth Core (Authentification) ---
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # --- Allauth Providers (Réseaux sociaux) ---
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.github',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'JobPilot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# --- Moteurs d'authentification ---
AUTHENTICATION_BACKENDS = [
    # Nécessaire pour se connecter par mot de passe (et accéder à l'admin)
    'django.contrib.auth.backends.ModelBackend',

    # Nécessaire pour que Allauth gère les connexions Google, LinkedIn, GitHub
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'JobPilot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'jobpilot_db'),
        'USER': os.getenv('DB_USER', 'axel'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),  # 'localhost' en local, 'db' dans Docker
        'PORT': os.getenv('DB_PORT', '5433'),  # Port 5433 pour Docker, 5432 si PostgresSQL local
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('email', 'first_name', 'last_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# --- 3. CONFIGURATION FRANCE TRAVAIL (Via .env) ---
CLIENT_ID = os.getenv('ID_CLIENT')
CLIENT_SECRET_KEY = os.getenv('CLIENT_SECRET')
API_URL = os.getenv('API_BASE_URL')

# --- 4. STRIPE (Via .env) ---
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
# Price IDs créés dans le Dashboard Stripe (Produits > Prix)
STRIPE_PRICE_PASS24H = os.getenv('STRIPE_PRICE_PASS24H')   # Paiement unique 2,99 €
STRIPE_PRICE_SPRINT = os.getenv('STRIPE_PRICE_SPRINT')      # Abonnement 5,99 € / semaine
STRIPE_PRICE_PRO = os.getenv('STRIPE_PRICE_PRO')           # Abonnement 14,99 € / mois
STRIPE_PRICE_PACK = os.getenv('STRIPE_PRICE_PACK')         # Paiement unique 4,99 € (10 crédits)

# --- Rate limiting API Gemini (Dev Free Tier vs Prod) ---
GEMINI_MAX_RPM = int(os.getenv('GEMINI_MAX_RPM'))           # Requêtes/minute globales (défaut 10 pour Free Tier)
GEMINI_FAIR_USE_LIMIT = int(os.getenv('GEMINI_FAIR_USE_LIMIT'))  # Requêtes/heure par utilisateur

AUTH_USER_MODEL = 'users.CustomUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Elle dit : "En production, rassemble tout dans le dossier 'staticfiles' à la racine."
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Permet à WhiteNoise de compresser les fichiers pour que le site charge plus vite
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Dossiers où Django va chercher tes fichiers CSS/JS personnalisés
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuration des fichiers médias (Uploads utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Azure Blob Storage pour les médias en production
if os.getenv("AZURE_ACCOUNT_NAME"):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.getenv("AZURE_ACCOUNT_NAME"),
                "account_key": os.getenv("AZURE_ACCOUNT_KEY"),
                "azure_container": os.getenv("AZURE_CONTAINER", "media"),
                # On garde juste l'expiration, ça suffit pour activer le SAS Token !
                "expiration_secs": 3600,
            },
        },
        "staticfiles": {
            # Attention, remets bien whitenoise ici pour tes images de design !
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # Plus besoin de AZURE_QUERYSTRING_AUTH ici non plus
    AZURE_URL_EXPIRATION_SECS = 3600  # 1 heure
    MEDIA_URL = (
        f"https://{os.getenv('AZURE_ACCOUNT_NAME')}.blob.core.windows.net/"
        f"{os.getenv('AZURE_CONTAINER', 'media')}/"
    )


LOGIN_REDIRECT_URL = 'post_login_loading'  # Page de chargement puis dashboard
LOGIN_URL = 'login'       # L'URL de la page de login (si accès refusé ailleurs)
# settings.py

# --- Email (dev : console pour voir les mails dans le terminal) ---
# --- Email (prod : envoie les mails via SMTP, ex. alertes JobAlert) ---
# En dev : utiliser SMTP si USE_SMTP_IN_DEV=true (pour tester l'envoi réel avec cron).
# Sinon en dev → console (mails affichés au terminal ; avec cron, le contenu va dans le log).
_use_smtp_in_dev = os.getenv("USE_SMTP_IN_DEV", "").lower() in ("true", "1", "yes")
if (DEBUG and ENVIRONMENT != "production") and not _use_smtp_in_dev:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Adresse qui apparaît comme expéditeur (ex. "JobPilot <noreply@votredomaine.com>")
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = os.getenv('SERVER_EMAIL')  # pour les erreurs envoyées aux admins

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# --- Allauth : email requis et vérification ---
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # ou 'optional' pour désactiver l'obligation


TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/8/tinymce.min.js'
TINYMCE_COMPRESSOR = False

# Configuration du système de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'file': {
            'format': '{levelname} {asctime} {name} {module} {funcName} {lineno} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'jobpilot.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'file',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'file',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'resumes': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'matching': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'dashboard': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# En production (ex. Azure App Service), pas de répertoire logs/ inscriptible → logs vers la console
if ENVIRONMENT == 'production':
    LOGGING['handlers']['file'] = {
        'level': 'INFO',
        'class': 'logging.StreamHandler',
        'formatter': 'file',
    }
    LOGGING['handlers']['error_file'] = {
        'level': 'ERROR',
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    }

SITE_ID = 1

# --- Allauth : adaptateur personnalisé (remplit email, first_name, last_name depuis Google/GitHub) ---
SOCIALACCOUNT_ADAPTER = "users.adapters.CustomSocialAccountAdapter"

# Scopes pour récupérer profil et email auprès des providers
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
    "github": {
        "SCOPE": ["read:user", "user:email"],
    },
    'linkedin_oauth2': {
        'SCOPE': ['openid', 'profile', 'email'],
    }
}

# Désactive la confirmation pour le login social
SOCIALACCOUNT_LOGIN_ON_GET = True

# Permet de lier automatiquement un compte social
# à un compte classique existant s'ils ont la même adresse e-mail pour éviter la collision d'email.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

#Permet de passer l'écran de vérification
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# On force Django à utiliser l'E-MAIL pour se connecter
ACCOUNT_AUTHENTICATION_METHOD = 'email'

