# Generated by Django 5.2.10 on 2026-02-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ai_credits',
            field=models.IntegerField(default=5, verbose_name='Crédits IA'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('pass24h', 'Pass 24h'), ('sprint', 'Sprint'), ('pro', 'Pro')], max_length=20, null=True, verbose_name="Type d'abonnement"),
        ),
    ]
