# Generated by Django 5.2.10 on 2026-02-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_username_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='temp_user', max_length=150, unique=True),
        ),
    ]
