# Generated by Django 5.2.10 on 2026-08-14 22:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Coupe l'accès au site pour tout le monde sauf l'équipe (is_staff).", verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(blank=True, default='JobPilot-AI est en maintenance. Nous revenons très vite.', verbose_name='Message de maintenance')),
                ('registrations_open', models.BooleanField(default=True, help_text="Si décoché, la page d'inscription refuse les nouveaux comptes.", verbose_name='Inscriptions ouvertes')),
                ('signup_free_credits', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name="Crédits IA offerts à l'inscription")),
                ('max_resumes_per_user', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Nombre de CV maximum par utilisateur')),
                ('matching_min_score', models.PositiveIntegerField(default=70, help_text="Seuil en dessous duquel une offre n'est pas proposée au candidat.", validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Score de matching minimum (%)')),
                ('alerts_enabled', models.BooleanField(default=True, help_text="Coupe globalement l'envoi des emails de `check_new_offers`.", verbose_name='Alertes nouvelles offres activées')),
                ('alerts_max_offers_per_email', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name="Nombre d'offres maximum par email d'alerte")),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email de contact affiché')),
                ('support_notice', models.CharField(blank=True, default='', help_text='Laisser vide pour ne rien afficher aux utilisateurs.', max_length=255, verbose_name="Bandeau d'information (public)")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Commande')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('success', 'Succès'), ('error', 'Échec')], default='running', max_length=20, verbose_name='Statut')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('items_processed', models.IntegerField(default=0, verbose_name='Éléments traités')),
                ('message', models.TextField(blank=True, verbose_name='Message / erreur')),
            ],
            options={
                'verbose_name': 'Exécution de tâche',
                'verbose_name_plural': 'Exécutions de tâches',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['name', '-started_at'], name='administrat_name_542cad_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('settings_updated', 'Paramètres modifiés'), ('user_viewed', 'Fiche utilisateur consultée'), ('user_deactivated', 'Utilisateur désactivé'), ('user_reactivated', 'Utilisateur réactivé'), ('credits_granted', 'Crédits accordés'), ('subscription_extended', 'Abonnement prolongé'), ('alert_toggled', 'Alerte activée/désactivée'), ('export_run', 'Export de données')], max_length=40, verbose_name='Action')),
                ('target', models.CharField(blank=True, help_text="Libellé de l'objet concerné (ex. « utilisateur #42 »).", max_length=255, verbose_name='Cible')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': "Entrée du journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='administrat_created_17c980_idx'), models.Index(fields=['action', '-created_at'], name='administrat_action_13a96d_idx')],
            },
        ),
    ]
