# Generated by Django 5.2.10 on 2026-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='semantic_matching_enabled',
            field=models.BooleanField(default=False, help_text="Décoché : le score par mots-clés pilote l'affichage, le score sémantique est calculé en parallèle sans être montré. Cochez une fois la comparaison des deux scores jugée concluante.", verbose_name='Matching sémantique actif'),
        ),
    ]
