# Generated by Django 5.2.10 on 2026-08-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_sitesettings_semantic_matching_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text="Tel qu'accepté par la personne, par exemple « Lucas B. ».", max_length=80, verbose_name='Nom affiché')),
                ('author_role', models.CharField(help_text='Par exemple « Développeur full-stack, recruté en mars 2026 ».', max_length=120, verbose_name='Poste / situation')),
                ('quote', models.TextField(help_text='Citation littérale. Ne pas reformuler à la place de la personne.', verbose_name='Témoignage')),
                ('result_metric', models.CharField(blank=True, help_text='Chiffre vérifiable issu du témoignage : « 3 entretiens en 2 semaines ».', max_length=120, verbose_name='Résultat mesurable')),
                ('consent_reference', models.CharField(help_text="Où retrouver l'accord écrit : date et objet du mail, lien, référence interne.", max_length=200, verbose_name="Preuve d'accord")),
                ('is_published', models.BooleanField(default=False, help_text="Décoché tant que l'accord n'est pas obtenu et vérifié.", verbose_name='Publié')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Témoignage client',
                'verbose_name_plural': 'Témoignages clients',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
