# Generated by Django 5.2.10 on 2026-08-17 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(db_index=True, max_length=20, verbose_name='Niveau')),
                ('logger_name', models.CharField(blank=True, max_length=120, verbose_name='Logger')),
                ('module', models.CharField(blank=True, max_length=120, verbose_name='Module')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ligne')),
                ('message', models.TextField(verbose_name='Message')),
                ('traceback', models.TextField(blank=True, verbose_name='Trace')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Méthode')),
                ('user_id_ref', models.PositiveIntegerField(blank=True, help_text="Identifiant seul, sans clé étrangère : purger un compte ne doit pas effacer la trace de l'incident.", null=True, verbose_name='Utilisateur concerné')),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Empreinte')),
                ('occurrences', models.PositiveIntegerField(default=1, verbose_name='Occurrences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Première occurrence')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière occurrence')),
            ],
            options={
                'verbose_name': 'Erreur applicative',
                'verbose_name_plural': 'Erreurs applicatives',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['-last_seen_at'], name='errorlog_seen_idx'), models.Index(fields=['fingerprint', '-last_seen_at'], name='errorlog_fp_idx')],
            },
        ),
    ]
