# Generated by Django 5.2.10 on 2026-01-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mon CV', max_length=100, verbose_name='Titre du CV')),
                ('file', models.FileField(upload_to='cvs/', verbose_name='Fichier PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('parsed_skills', models.JSONField(blank=True, default=list, verbose_name='Compétences détectées')),
                ('parsed_data', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées IA')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
