# Generated by Django 5.2.10 on 2026-01-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_add_detected_job_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='parsed_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Compétences détectées (legacy)'),
        ),
    ]
