# Generated by Django 5.2.10 on 2026-08-14 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_alter_resume_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', '-uploaded_at'], name='resume_user_uploaded_idx'),
        ),
    ]
