# Generated by Django 5.2.10 on 2026-08-15 10:05

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_resume_resume_user_uploaded_idx'),
    ]

    operations = [
        # `CREATE EXTENSION IF NOT EXISTS vector` : sans elle, la création
        # des colonnes vectorielles échoue. Idempotente.
        VectorExtension(),
        migrations.AddField(
            model_name='resume',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vectorisé le'),
        ),
        migrations.AddField(
            model_name='resume',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Vecteur sémantique'),
        ),
        migrations.AddField(
            model_name='resume',
            name='embedding_fingerprint',
            field=models.CharField(blank=True, max_length=64, verbose_name='Empreinte du texte vectorisé'),
        ),
    ]
