"""
Django settings for JobPilot project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Ce fichier vit dans JobPilot/settings/, soit trois niveaux sous la racine
# du dépôt (settings → JobPilot → racine).
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")


if not SECRET_KEY:
    raise RuntimeError(
        "SECRET_KEY manquante. "
        "Définissez la variable d’environnement SECRET_KEY (ou DJANGO_SECRET_KEY)."
    )

def env_bool(name, default=False):
    """Lit un booléen depuis l'environnement sans planter si la variable manque."""
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("true", "1", "yes", "on")


def env_int(name, default):
    """Lit un entier depuis l'environnement ; retombe sur `default` si absent ou invalide."""
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return int(raw)
    except ValueError:
        return default


# SECURITY WARNING: don't run with debug turned on in production!
# Défaut à False : une variable oubliée doit produire un site sûr, pas un site
# en mode debug exposant les tracebacks.
DEBUG = env_bool("DEBUG", default=False)
ENVIRONMENT = (os.getenv("ENVIRONMENT") or "development").strip().lower()
# Sécurité HTTPS uniquement en production (évite la redirection HTTPS avec runserver en local)
_PROD_SECURITY = (not DEBUG) and (ENVIRONMENT == "production")

# Paramètres de sécurité (toujours définis pour satisfaire check —deploy)
SECURE_SSL_REDIRECT = _PROD_SECURITY
SESSION_COOKIE_SECURE = _PROD_SECURITY
CSRF_COOKIE_SECURE = _PROD_SECURITY
SECURE_HSTS_SECONDS = 31536000 if _PROD_SECURITY else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = _PROD_SECURITY
SECURE_HSTS_PRELOAD = _PROD_SECURITY
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if _PROD_SECURITY else None

# Configuration du domaine du site
SITE_URL = os.getenv('SITE_URL', 'https://jobpilot-ai.fr')
# Extraire le nom de domaine pour ALLOWED_HOSTS (sans https://)
_site_domain = SITE_URL.replace('https://', '').replace('http://', '').rstrip('/')

if _PROD_SECURITY:
    ALLOWED_HOSTS = [_site_domain, f'www.{_site_domain}']
else:
    ALLOWED_HOSTS = ['*']
# --- En-têtes de sécurité ---
# Bascule la CSP en observation (violations signalées, rien de bloqué) le temps
# de valider une modification de gabarit introduisant une origine tierce.
CSP_REPORT_ONLY = env_bool('CSP_REPORT_ONLY', default=False)

# --- Analytics ---
# Identifiant de mesure GA4 (format G-XXXXXXXXXX). Vide => aucun script chargé.
GA_MEASUREMENT_ID = os.getenv('GA_MEASUREMENT_ID', '').strip()

CSRF_TRUSTED_ORIGINS = [
    'https://autohypnotic-lashay-undecretory.ngrok-free.dev',
    SITE_URL,
    'https://jobpilot-ai.fr',
    'https://www.jobpilot-ai.fr'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'users.apps.UsersConfig',
    'resumes',
    'matching',
    'dashboard',
    'subscriptions',
    'administration',

# --- Allauth Core (Authentification) ---
    'allauth',
    'allauth.account',
    'allauth.socialaccount',

    # --- Allauth Providers (Réseaux sociaux) ---
    'allauth.socialaccount.providers.google',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise doit venir juste après SecurityMiddleware : un fichier statique
    # est alors servi sans traverser sessions, CSRF ni authentification.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # Compression texte des réponses HTML/JSON produites par Django (les
    # statiques, eux, sont précompressés à la volée par WhiteNoise).
    # BREACH : Django masque le jeton CSRF différemment à chaque réponse depuis
    # la 4.1, ce qui neutralise l'attaque classique sur formulaire compressé.
    'django.middleware.gzip.GZipMiddleware',
    'JobPilot.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    # Doit rester après AuthenticationMiddleware : le mode maintenance laisse
    # passer l'équipe, ce qui suppose que request.user est déjà résolu.
    'administration.middleware.MaintenanceModeMiddleware',
]

ROOT_URLCONF = 'JobPilot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'administration.context_processors.site_settings',
                'JobPilot.context_processors.seo',
            ],
        },
    },
]

# --- Moteurs d'authentification ---
AUTHENTICATION_BACKENDS = [
    # Nécessaire pour se connecter par mot de passe (et accéder à l'admin)
    'django.contrib.auth.backends.ModelBackend',

    # Nécessaire pour que Allauth gère les connexions Google, LinkedIn, GitHub
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'JobPilot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'jobpilot_db'),
        'USER': os.getenv('DB_USER', 'axel'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),  # 'localhost' en local, 'db' dans Docker
        'PORT': os.getenv('DB_PORT', '5433'),  # Port 5433 pour Docker, 5432 si PostgresSQL local
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('email', 'first_name', 'last_name'),
            'max_similarity': 0.7,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# --- 3. CONFIGURATION FRANCE TRAVAIL (Via .env) ---
CLIENT_ID = os.getenv('ID_CLIENT')
CLIENT_SECRET_KEY = os.getenv('CLIENT_SECRET')
API_URL = os.getenv('API_BASE_URL')

# --- 4. STRIPE (Via .env) ---
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')
# Price IDs créés dans le Dashboard Stripe (Produits > Prix)
STRIPE_PRICE_PASS24H = os.getenv('STRIPE_PRICE_PASS24H')   # Paiement unique 2,99 €
STRIPE_PRICE_SPRINT = os.getenv('STRIPE_PRICE_SPRINT')      # Abonnement 5,99 € / semaine
STRIPE_PRICE_PRO = os.getenv('STRIPE_PRICE_PRO')           # Abonnement 14,99 € / mois
STRIPE_PRICE_PACK = os.getenv('STRIPE_PRICE_PACK')         # Paiement unique 4,99 € (10 crédits)

# --- Rate limiting API Gemini (Dev Free Tier vs Prod) ---
GEMINI_MAX_RPM = env_int('GEMINI_MAX_RPM', 10)              # Requêtes/minute globales (10 pour le Free Tier)
GEMINI_FAIR_USE_LIMIT = env_int('GEMINI_FAIR_USE_LIMIT', 50)  # Requêtes/heure par utilisateur

AUTH_USER_MODEL = 'users.CustomUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Elle dit : "En production, rassemble tout dans le dossier 'staticfiles' à la racine."
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Permet à WhiteNoise de compresser les fichiers pour que le site charge plus vite
# (gzip *et* brotli grâce à l'extra `whitenoise[brotli]` : le .br est ~20 % plus
# petit que le .gz sur du CSS, et tous les navigateurs visés l'acceptent).
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Les fichiers statiques portent une empreinte dans leur nom (stockage manifeste) :
# ils sont donc immuables et peuvent être mis en cache un an.
WHITENOISE_MAX_AGE = 31536000

# Dossiers où Django va chercher tes fichiers CSS/JS personnalisés
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuration des fichiers médias (Uploads utilisateurs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Limite la taille des requêtes/uploads pour éviter l'épuisement des ressources (DoS)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 Mo
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 Mo

# Azure Blob Storage pour les médias en production
if os.getenv("AZURE_ACCOUNT_NAME"):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
            "OPTIONS": {
                "account_name": os.getenv("AZURE_ACCOUNT_NAME"),
                "account_key": os.getenv("AZURE_ACCOUNT_KEY"),
                "azure_container": os.getenv("AZURE_CONTAINER", "media"),
                # On garde juste l'expiration, ça suffit pour activer le SAS Token !
                "expiration_secs": 3600,
            },
        },
        "staticfiles": {
            # Attention, remets bien whitenoise ici pour tes images de design !
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # Plus besoin de AZURE_QUERYSTRING_AUTH ici non plus
    AZURE_URL_EXPIRATION_SECS = 3600  # 1 heure
    MEDIA_URL = (
        f"https://{os.getenv('AZURE_ACCOUNT_NAME')}.blob.core.windows.net/"
        f"{os.getenv('AZURE_CONTAINER', 'media')}/"
    )


LOGIN_REDIRECT_URL = 'post_login_loading'  # Page de chargement puis dashboard
LOGIN_URL = 'login'       # L'URL de la page de login (si accès refusé ailleurs)
# settings.py

# --- Email (dev : console pour voir les mails dans le terminal) ---
# --- Email (prod : envoie les mails via SMTP, ex. alertes JobAlert) ---
# En dev : utiliser SMTP si USE_SMTP_IN_DEV=true (pour tester l'envoi réel avec cron).
# Sinon en dev → console (mails affichés au terminal ; avec cron, le contenu va dans le log).
_use_smtp_in_dev = os.getenv("USE_SMTP_IN_DEV", "").lower() in ("true", "1", "yes")
if (DEBUG and ENVIRONMENT != "production") and not _use_smtp_in_dev:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Adresse qui apparaît comme expéditeur (ex. "JobPilot <noreply@votredomaine.com>")
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = os.getenv('SERVER_EMAIL')  # pour les erreurs envoyées aux admins

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# --- Allauth : email requis et vérification ---
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # ou 'optional' pour désactiver l'obligation


TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/8/tinymce.min.js'
TINYMCE_COMPRESSOR = False

# Configuration du système de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'file': {
            'format': '{levelname} {asctime} {name} {module} {funcName} {lineno} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'jobpilot.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'file',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'file',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose',
        },
        # Erreurs en base : en production les fichiers de logs n'existent pas
        # (sortie standard), le back-office n'avait donc rien à afficher.
        'db_errors': {
            'level': 'ERROR',
            'class': 'administration.services.log_handler.DatabaseErrorHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['error_file', 'mail_admins', 'db_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'resumes': {
            'handlers': ['console', 'file', 'error_file', 'db_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'matching': {
            'handlers': ['console', 'file', 'error_file', 'db_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'dashboard': {
            'handlers': ['console', 'file', 'error_file', 'db_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'administration': {
            'handlers': ['console', 'file', 'error_file', 'db_errors'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# En production (ex. Azure App Service), pas de répertoire logs/ inscriptible → logs vers la console
if ENVIRONMENT == 'production':
    LOGGING['handlers']['file'] = {
        'level': 'INFO',
        'class': 'logging.StreamHandler',
        'formatter': 'file',
    }
    LOGGING['handlers']['error_file'] = {
        'level': 'ERROR',
        'class': 'logging.StreamHandler',
        'formatter': 'verbose',
    }

SITE_ID = 1

# --- Allauth : adaptateur personnalisé (remplit email, first_name, last_name depuis Google) ---
SOCIALACCOUNT_ADAPTER = "users.adapters.CustomSocialAccountAdapter"

# Scopes pour récupérer profil et email auprès des providers
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
    },
}

# Désactive la confirmation pour le login social
SOCIALACCOUNT_LOGIN_ON_GET = True

# Permet de lier automatiquement un compte social
# à un compte classique existant s'ils ont la même adresse e-mail pour éviter la collision d'email.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

#Permet de passer l'écran de vérification
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"

# On force Django à utiliser l'E-MAIL pour se connecter
ACCOUNT_LOGIN_METHODS = {'email'}



# ---------------------------------------------------------------------------
# CACHE
# ---------------------------------------------------------------------------
# Trois mécanismes critiques s'appuient sur le cache : le compteur RPM global
# de Gemini, le quota horaire par utilisateur et le token OAuth France Travail.
# Avec LocMemCache (le défaut Django), chaque worker gunicorn a son propre
# compteur : la limite « 10 req/min » devient 10 × nombre de workers, et le
# garde-fou anti-dépassement de quota ne protège plus rien.
#
# REDIS_URL doit donc être défini dès qu'il y a plus d'un worker. Les modules
# prod.py / dev.py décident quoi faire en son absence.
REDIS_URL = os.getenv("REDIS_URL")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
} if REDIS_URL else {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "jobpilot-locmem",
    }
}


# ---------------------------------------------------------------------------
# TÂCHES DE FOND (Celery)
# ---------------------------------------------------------------------------
# Les appels IA et les recherches d'offres ne doivent pas s'exécuter dans le
# cycle requête/réponse : ils durent plusieurs secondes et bloquent un worker
# web pendant tout ce temps.
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL or "")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", REDIS_URL or "")

# Sans broker configuré, les tâches s'exécutent en direct (comportement actuel).
# Cela garantit qu'un environnement sans Redis reste fonctionnel plutôt que de
# tomber en erreur au premier appel.
CELERY_TASK_ALWAYS_EAGER = not CELERY_BROKER_URL
CELERY_TASK_EAGER_PROPAGATES = True

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Garde-fous : une tâche qui dépasse ces durées est tuée plutôt que de
# monopoliser un worker indéfiniment.
CELERY_TASK_SOFT_TIME_LIMIT = env_int("CELERY_TASK_SOFT_TIME_LIMIT", 120)
CELERY_TASK_TIME_LIMIT = env_int("CELERY_TASK_TIME_LIMIT", 180)
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# --- Économie de commandes (brokers Redis serverless) ---------------------
# Upstash et consorts facturent à la commande, avec une offre gratuite
# plafonnée. Or un worker Celery au repos bavarde beaucoup : sondage de la
# file, battements de cœur, découverte des autres workers. Sans réglage, un
# worker inactif peut épuiser un quota quotidien sans avoir traité une seule
# tâche.
#
# On espace le sondage à 2 s : une génération de lettre dure plusieurs
# secondes, 2 s d'attente supplémentaire ne se remarquent pas, et le nombre
# de commandes est divisé par quatre par rapport au défaut de 0,5 s.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "polling_interval": 2.0,
    # Au-delà, une tâche non acquittée est rendue à la file. Doit rester
    # supérieur à CELERY_TASK_TIME_LIMIT, sinon une tâche lente serait
    # réexécutée alors qu'elle tourne encore.
    "visibility_timeout": 600,
    "socket_keepalive": True,
}

# Les résultats sont lus une fois par le navigateur, puis inutiles. Une heure
# suffit largement et réduit d'autant le stockage sollicité.
CELERY_RESULT_EXPIRES = int(os.getenv("CELERY_RESULT_EXPIRES", "3600"))


