# Generated by Django 5.2.10 on 2026-01-20 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=50, unique=True, verbose_name='ID France Travail')),
                ('title', models.CharField(max_length=255, verbose_name='Intitulé du poste')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Entreprise')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('url', models.URLField(max_length=500, verbose_name='Lien offre')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('contract_type', models.CharField(blank=True, max_length=50, verbose_name='Type de contrat')),
                ('date_posted', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_api_data', models.JSONField(default=dict, verbose_name='Données brutes API')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Score de matching')),
                ('status', models.CharField(choices=[('new', 'Nouveau match'), ('seen', 'Vu'), ('applied', 'Postulé'), ('rejected', 'Rejeté par candidat')], default='new', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.joboffer')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('user', 'job_offer')},
            },
        ),
    ]
