# Generated by Django 5.2.10 on 2026-01-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='cover_letter_content',
            field=models.TextField(blank=True, verbose_name='Lettre de motivation'),
        ),
    ]
