# Generated by Django 5.2.10 on 2026-01-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_jobmatch_cover_letter_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Lien offre'),
        ),
    ]
