# Generated by Django 5.2.10 on 2026-01-22 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_joboffer_url'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='resumes.resume'),
        ),
    ]
