# Generated by Django 5.2.10 on 2026-08-14 22:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_jobmatch_is_unlocked'),
        ('resumes', '0005_resume_resume_user_uploaded_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['user', 'is_unlocked', '-score'], name='jobmatch_user_unlocked_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['resume', 'is_unlocked'], name='jobmatch_resume_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmatch',
            index=models.Index(fields=['status', '-matched_at'], name='jobmatch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['-created_at'], name='joboffer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=models.Index(fields=['-date_posted'], name='joboffer_posted_idx'),
        ),
    ]
