# Generated by Django 5.2.10 on 2026-08-15 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_jobmatch_jobmatch_user_unlocked_idx_and_more'),
        ('subscriptions', '0003_creditentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True, verbose_name='Identifiant de tâche')),
                ('operation', models.CharField(max_length=50, verbose_name='Opération')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Terminé'), ('failure', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Résultat')),
                ('error', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('error_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Code HTTP équivalent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Création')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('credit_entry', models.ForeignKey(blank=True, help_text='Débit associé, remboursé automatiquement si la tâche échoue.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='subscriptions.creditentry', verbose_name='Écriture de crédit')),
                ('job_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='matching.jobmatch', verbose_name='Candidature concernée')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Traitement IA',
                'verbose_name_plural': 'Traitements IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='aijob_user_idx'), models.Index(fields=['status', '-created_at'], name='aijob_status_idx')],
            },
        ),
    ]
