# Generated by Django 5.2.10 on 2026-08-15 10:05

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_aijob'),
    ]

    operations = [
        # `CREATE EXTENSION IF NOT EXISTS vector` : sans elle, la création
        # des colonnes vectorielles échoue. Idempotente.
        VectorExtension(),
        migrations.AddField(
            model_name='jobmatch',
            name='semantic_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score sémantique'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vectorisée le'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Vecteur sémantique'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='embedding_fingerprint',
            field=models.CharField(blank=True, help_text="Évite de recalculer le vecteur quand le contenu n'a pas changé.", max_length=64, verbose_name='Empreinte du texte vectorisé'),
        ),
        migrations.AddIndex(
            model_name='joboffer',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='joboffer_embedding_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
