# Generated by Django 5.2.10 on 2026-08-14 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Négatif pour une consommation, positif pour un ajout.', verbose_name='Mouvement')),
                ('reason', models.CharField(choices=[('signup', "Crédits offerts à l'inscription"), ('purchase', 'Achat'), ('admin_grant', "Ajustement par l'équipe"), ('consumption', 'Consommation'), ('refund', 'Remboursement après échec')], max_length=20, verbose_name='Motif')),
                ('operation', models.CharField(blank=True, help_text="Action à l'origine du mouvement (ex. « generate_letter »).", max_length=50, verbose_name='Opération')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Précision')),
                ('balance_after', models.IntegerField(blank=True, help_text="Photographie du solde, pour repérer une dérive sans rejouer tout l'historique.", null=True, verbose_name='Solde après écriture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('reverses', models.ForeignKey(blank=True, help_text='Renseigné sur un remboursement : pointe la consommation annulée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='subscriptions.creditentry', verbose_name="Annule l'écriture")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de crédit',
                'verbose_name_plural': 'Registre des crédits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='creditentry_user_idx'), models.Index(fields=['reason', '-created_at'], name='creditentry_reason_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='creditentry_delta_non_nul')],
            },
        ),
    ]
